usd: Support arrays in "extraPlugInfo" dictionary in usdGenSchema
usdGenSchema would emit errors like the following when it encountered
an array in the "extraPlugInfo" dictionary authored in a schema.usda:

  ERROR: Object of type StringArray is not JSON serializable

This was because the dictionary retrieved from the schema layer was
passed directly to the json encoder, which did not know how to handle
the Vt.Array values contained inside. usdGenSchema now converts these
arrays to regular Python lists.

This issue was uncovered in change 2417301 but was unfortunately
not flagged by automated testing. usd's plugInfo.json was regenerated
with this fix, but all diffs are just formatting changes.

(Internal change: 2417962)